---
title: "team"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
gss <- readxl::read_xls('/Users/juliahernesman/Downloads/GSS.xls')
library(ggplot2)
library(tidyverse)

gss %>% rename(
  year = `Gss year for this respondent`,
  happy = `General happiness`,
  party = `Political party affiliation`,
  race = `Race of respondent`,
  sex = `Respondents sex`,
  cdegree = `When received college degree`,
  hsdegree = `When received hs degree`,
  momdegree = `Mothers highest degree`,
  daddegree = `Fathers highest degree`,
  schoolyears = `Highest year of school completed`,
  age = `Age of respondent`,
  maried = `Marital status`,
  id = `Respondent id number`,
  balot = `Ballot used for interview`) -> gss
str(gss)

gss$schoolyears <- as.numeric(gss$schoolyears)
gss$age <- as.numeric(gss$age)

#1
by_party <-group_by(gss, party)
ggplot(gss, aes(x=party, y=schoolyears)) + geom_boxplot()

#2
betterEd <- gss %>% group_by(party) %>% filter(schoolyears > median(schoolyears, na.rm = TRUE))
str(betterEd)

#3
dat1 <- gss[gss$happy %in% c('Pretty happy', 'Very happy', 'Not too happy'),]
dat2 <- dat1[dat1$maried %in% c('Married', 'Never married', 'Divorced'),]
ggplot(dat2, aes(x=maried , fill=happy)) + geom_bar(position='fill')

#4
ggplot(dat2, aes(x=maried , fill=happy)) + geom_bar(position='fill') + facet_grid(party)

#5
gss$schoolyrcat[gss$schoolyears < 12] <- "less education"
gss$schoolyrcat[gss$schoolyears >= 12] <- "more education"
dat3 <- gss[gss$maried %in% c('Married', 'Never married', 'Divorced'),]
dat4 <- dat3[dat3$schoolyrcat %in% c('less education', 'more education'),]
ggplot(dat4, aes(x=schoolyrcat , fill=maried)) + geom_bar(position='fill')
```
##


```{r}
dat5 <- gss[gss$happy %in% c('Very happy', 'Pretty happy', 'Not too happy'),]
dat6 <- dat5[dat5$schoolyrcat %in% c('less education', 'more education'),]
ggplot(dat6, aes(x=schoolyrcat , fill=happy)) + geom_bar(position='fill')
```
##There are less people "not too happy" that have more education. In other words people that have more schooling tend to be happier.